name: ci 
on:
  push:
    branches:
      - master 
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material
      - run: pip install 'mkdocstrings[python]'
      - run: pip install . # install local mecode
      - run: pip install mike
      # Install hatch
      - run: pip install hatch  # Ensure hatch is installed

      # Step to get version dynamically using hatch
      - name: Get version from hatch
        id: get_version
        run: |
          VERSION=$(hatch version)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Version: $VERSION"
      
      - run: mkdocs build  # Build the documentation
      - run: mike deploy ${{ env.VERSION }} -m "Deploy version ${{ env.VERSION }}" --update-aliases latest  # Deploy using mike
